// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  logo_topBar: require('../Images/logo_topBar.png'),
  logo_transparent: require('../Images/logo_transparent.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  noPart: require('../Images/Parts/no_part.png'),
  part: [
    require('../Images/Parts/part-2.png'),
    require('../Images/Parts/part-2.png'),
    require('../Images/Parts/part-2.png'),
    require('../Images/Parts/part-2.png'),
    require('../Images/Parts/part-4.png'),
    require('../Images/Parts/part-5.png'),
    require('../Images/Parts/part-6.png'),
    require('../Images/Parts/part-7.png'),
    require('../Images/Parts/part-8.png'),
    require('../Images/Parts/part-9.png'),
    require('../Images/Parts/part-10.png'),
  ]
}

export default images
